# Generated by Django 5.2.7 on 2025-10-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diligencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diligencia',
            options={'verbose_name': 'Diligência', 'verbose_name_plural': 'Diligências'},
        ),
    ]
